### ISSUE TITLE
`android_application` rule doesn't support `select` statements for `manifest_values` field

### ISSUE THREAD

**Issue by jchen-sc** [bazelbuild/rules_android#155]
**Background**
The current implementation [android_application_macro](https://github.com/bazelbuild/rules_android/blob/7b6e8cc612c410d90c62dd8fb0ce3cc6d125c642/rules/android_application/android_application_rule.bzl#L349C5-L392) doesn't support using `select` statement in targets  for `manifest_values` field.

For example, if I define a target like this
```
android_application(
    name = "release-app-bundle",
    debug_key = "//scripts/keystore:andy-keystore",
    excludes = PACKAGE_EXCLUDE_LIST,
    feature_modules = FEATURE_MODULES,
    manifest_values = select({
        "//bzl/conditions:build_type_alpha": {
            "appName": "@string/app_name",
            "debuggable": "false",
            "versionName": "'{} {}'".format(VERSION_NUMBER, "ALPHA"),
        },
        "//conditions:default": {
            "appName": "@string/app_name_bazel",
        },
    }),
    ...
)
```

The build will fail with error message 
```
ERROR: Traceback (most recent call last):
File "apps/mushroom/apk/BUILD.bazel", line 806, column 20, in <toplevel>
android_application(
File "bzl/macros/android.bzl", line 49, column 29, in android_application
_android_application(**kwargs)
File "26a6608cebb0ef5e1c9ff08eedd1ef74/external/build_bazel_rules_android/rules/android_application/android_application.bzl", line 48, column 31, in android_application
_android_application_macro(
File "26a6608cebb0ef5e1c9ff08eedd1ef74/external/build_bazel_rules_android/rules/android_application/android_application_rule.bzl", line 516, column 18, in android_application_macro
_verify_attrs(attrs, fqn)
File "26a6608cebb0ef5e1c9ff08eedd1ef74/external/build_bazel_rules_android/rules/android_application/android_application_rule.bzl", line 67, column 44, in _verify_attrs
if not attrs.get("manifest_values", {}).get("applicationId"):
Error: 'select' value has no field or method 'get'
```

Even if we commented out the `_verify_attrs` methods from the rule, the build will still fail on other steps 
```
File "build_bazel_rules_android/rules/android_application/android_application.bzl", line 48, column 31, in android_application
_android_application_macro(
File "build_bazel_rules_android/rules/android_application/android_application_rule.bzl", line 566, column 70, in android_application_macro
application_id = getattr(attrs_struct, "manifest_values", {})["applicationId"],
Error: type 'select' has no operator [](string)
```

**Expected Behavior**
`android_application` rule shouldn't fail when we are using `select` statement on any field.

**Comment by nkoroste** [comment]
@ahumesky @ted-xie thoughts on fixing this?

**Comment by ahumesky** [comment]
we have a fix for this we'll be submitting soon/this week

**Comment by nkoroste** [comment]
Thanks for the fix, I'm going to try it soon. 

BTW it would be also nice to select on the following attr as well https://github.sc-corp.net/Snapchat/bazel/blob/main/src/main/java/com/google/devtools/build/lib/rules/android/AndroidRuleClasses.java#L794 I assume it would be possible when the starlark version is ready?

**Comment by ahumesky** [comment]
I don't think starlarkification will help with that particular attribute. It's non-configurable because it's used in this implicit outputs function:
https://github.com/bazelbuild/bazel/blob/a7b1d3662e63a180f5d8d9b9188eac2aa486d02d/src/main/java/com/google/devtools/build/lib/rules/android/AndroidRuleClasses.java#L276

The same implicit outputs are available to starlark rules (although it's deprecated):
https://bazel.build/rules/lib/globals/bzl#rule.outputs

and they have the same limitations around `select()` (although the UI is kind of worse: there's no way to say in starlark that an attribute is used in a starlark implicit outputs function, so everything will work until a `select()` is used with that attribute, and then bazel will error out)

For backwards compatibility / avoiding more migration, we'll likely use the same implicit outputs in the starlark version.
