### ISSUE TITLE
enforce_min_sdk_version requires lxml, which isn't present

### ISSUE THREAD

**Issue by katre** [bazelbuild/rules_android#179]
Since `lxml` was added in 45f3b886c5c999e38bf72108d00954b0ddf225d6, it needs to be declared as a dependency in WORKSPACE/MODULE.

With WORKSPACE, becuse rules_python uses the system python by default, users may or may not have `lxml` installed, but BazelCI does not: https://buildkite.com/bazel/rules-android/builds/2008#018b61eb-be83-46ac-9015-5db3e9d2bc5b

For MODULE.bazel, rules_python is hermetic, so it is definitely not present: https://buildkite.com/bazel/rules-android/builds/2008#018b61eb-be8e-4fde-b85d-75650e732b3e

I think the MODULE version is fine for downstream rules_android users, but the WORKSPACE change isn't: we need either a third stage macro (changing the current `rules_android_prereqs/rules_android_workspace` setup to `rules_android_prereqs/rules_android_workspace/rules_android_py_deps`).

How long will we support non-bzlmod users?

**Comment by ted-xie** [comment]
I wonder if we could just refactor enforce_min_sdk_floor to use the built-in python XML parser, rather than the third-party library. This in theory should be as simple as substituting [this line](https://github.com/bazelbuild/rules_android/blob/main/src/tools/enforce_min_sdk_floor/enforce_min_sdk_floor.py#L27) to `import xml.etree.ElementTree as ET`. A summary of the lxml differences can be found [here](https://lxml.de/1.3/compatibility.html); I think they should mostly be API-compatible, but it's unknown if enforce_min_sdk_floor uses any of the "extra" features such as XSLT.

**Comment by ted-xie** [comment]
> How long will we support non-bzlmod users?

In the most conservative estimation, we'd have to support non-bzlmod users for as long as the `--disable_bzlmod` flag exists in Bazel.

**Comment by katre** [comment]
The original version used python's built-in XML module, but it was switched to lxml to support keeping comments in the manifest before the first element, which cannot be done with the built-in module. See https://github.com/bazelbuild/rules_android/commit/45f3b886c5c999e38bf72108d00954b0ddf225d6 for details.
