### ISSUE TITLE
`android_sdk_repository` fails if non-integer platform level is installed

### ISSUE THREAD

**Issue by tdibattista** [bazelbuild/rules_android#182]
Android seems to now provide platforms in `sdkmanager` that don't follow the pattern `platforms;android-XX`. If one of these packages is installed, the starlark version of `android_sdk_repository` fails to initialize.

For example, with `platforms;android-TiramisuPrivacySandbox` installed, I get the following error:

```
ERROR: An error occurred during the fetch of repository 'androidsdk':
   Traceback (most recent call last):
	File "/home/tyler/.cache/bazel/_bazel_tyler/2cbdb241f61f078e4388015429901a72/external/rules_android/rules/android_sdk_repository/rule.bzl", line 104, column 34, in _android_sdk_repository_impl
		api_levels = _read_api_levels(repo_ctx, android_sdk_path)
	File "/home/tyler/.cache/bazel/_bazel_tyler/2cbdb241f61f078e4388015429901a72/external/rules_android/rules/android_sdk_repository/rule.bzl", line 49, column 24, in _read_api_levels
		level = int(name[len("android-"):])
Error in int: invalid base-10 literal: "TiramisuPrivacySandbox"

```

**Comment by ahumesky** [comment]
The crash is fixed, but note that there currently is no way to select a non-numeric API level from android_sdk_repository, because the api_level attribute is defined as an int: https://github.com/bazelbuild/rules_android/blob/abe2eddef60862cbfee407571f2848f840ffda49/rules/android_sdk_repository/rule.bzl#L163

and the "pick the max API level installed" logic used when api_level is not specified will only consider numeric API levels.

If this is a major blocker we can consider workarounds (what immediately comes to mind is to add an additional string-type attribute, make android_sdk_repository a macro which will inspect api_level to see if it's an int or a string, and then use the appropriate int or string type attribute with the real android_sdk_repository rule, for backwards compatibility)

**Comment by tdibattista** [comment]
Awesome! I could see this being a blocker in the future for others that need to use these platforms but my current issue is resolved. Thanks for the quick fix!
