### ISSUE TITLE
Bazel AndroidManifest merging doesn't preserve the correct order

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/rules_android#192]
The main difference between Gradle and Bazel manifest merging order is "If you have multiple libraries, their manifest priorities match the order they appear in your Gradle dependencies block." ([doc](https://developer.android.com/build/manage-manifests)) That means the manifest entries in library modules have higher priority than its dependency, which is not the case in bazel.

**Comment by nkoroste** [comment]
Might be related: https://github.com/bazelbuild/rules_android/pull/190

**Comment by nkoroste** [comment]
cc @ahumesky @ted-xie

**Comment by ahumesky** [comment]
I had considered just making "dependency order" the default for the bazel version of the rules (as #190 does, but adjusting so that internally we keep the sorting behavior) but it occurs to me that this would create a potential incompatibility between the native rules and the starlark rules, which could make migrating from native to starlark more complicated -- so we might need a switch in bazel anyway (as #193 does)

**Comment by ahumesky** [comment]
This should be addressed with https://github.com/bazelbuild/rules_android/commit/f13f24598d62afdd90f24bbd2777c6bba28ef17b

Note that the default is now to merge manifests in "dependency" order instead of what we're now calling "legacy" order (roughly alphabetical). The previous behavior can be enabled with `--@rules_android//rules/flags:manifest_merge_order=legacy`
