### ISSUE TITLE
Are these rules actively maintained?

### ISSUE THREAD

**Issue by c16a** [bazelbuild/rules_android#41]
The last commit I can see is around 15 months ago. Is the road map that was previously laid out, on track? We still have missing features such as AAB support.

**Comment by ahumesky** [comment]
The pre-alpha contains the in-progress release of the the Starlark rewrite of the Android rules. We put this on a separate branch because the initial commits wouldn't work out-of-the-box. It will still probably be a quarter or two before we merge the branch into main. For AAB, see https://github.com/bazelbuild/bazel/issues/11497
